---
# - hosts: servers
#   become: yes
#   become_user: root
#   become_method: sudo
#   vars:
#     ansible_become_pass: password
#   roles:
#     - prometheus_node_exporter

- hosts: controller
  become: yes
  become_user: ansible
  vars:
    ansible_become_pass: password
  roles:
    - prometheus_blackbox_exporter
    - prometheus